name = "Eig3x3"
version = "0.1.0"
defaultTargets = ["Eig3x3"]
testDriver = "eig3x3-tests"

[[lean_lib]]
name = "Eig3x3"
srcDir = "src"
globs = ["Eig3x3.*"]

[[lean_lib]]
name = "Tests"
srcDir = "tests"
globs = ["Tests.*"]

[[lean_exe]]
name = "eig3x3-tests"
root = "Main"
srcDir = "tests"

[[lean_exe]]
name = "eig3x3-cli"
root = "Cli"
srcDir = "tests"
